FRC2714/Reefscape-2025

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AlignToCoral.java
=> 2 ll 1 tag

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/CoralIntake.java
has working sim,
position PID wrapping needs to be tested with actual absolute encoder
=> Coral Intake

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/AlignToCoral.java, src/main/java/frc/robot/commands/AlignToProcessor.java, src/main/java/frc/robot/subsystems/Limelight.java
basically follows the aling to coral stuff
=> aling to processor command

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/subsystems/AlgaeIntake.java, src/main/java/frc/robot/subsystems/Elevator.java
=> got rid of some useless stutff

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/subsystems/Elevator.java
created a forward limit switch at max elevator position
=> added forward limit switch

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/subsystems/CoralIntake.java
* adds beam break
- no smarts just logging
* separates out indexer from roller
* refactors variables for the above
=> Coral intake updates

simgui-ds.json, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/StateMachine.java
Handoff, elevator, and coral intake manual override
=> Manual override

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/subsystems/CoralIntake.java
Updated CAN IDs and motor configurations
=> Updated configs

src/main/java/frc/robot/subsystems/StateMachine.java
based on #40. Merge that before this
This doesn't include implementation changes, just refactors:
* Adds robot wide states
* Log to smart dashboard
* Reorganizes methods
* Extracts some implementations into their own sequence commands
=> State machine clean up and refactor

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/StateMachine.java
Add these back if needed in the future
=> Remove unused subsystems from state machine

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/StateMachine.java, src/test/java/StateMachineTests.java
Changed state machine so robot can't transition to extake from any state.
May need to add more unit tests.
=> Extake only to and from poop standby in state machine

src/main/java/frc/robot/Configs.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/Dragon.java, src/main/java/frc/robot/subsystems/StateMachine.java, src/test/java/StateMachineTests.java
Need to get dragon free from elevator angle
=> Optimize state machine

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/CoralIntake.java
=> Fixes from drive testing

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/Dragon.java, src/main/java/frc/robot/subsystems/StateMachine.java, src/test/java/StateMachineTests.java
Fixed teleop default states and add test
=> Fix teleop default states

src/main/java/frc/robot/RobotContainer.java
Move intake command to driver controller and remove commented code
=> Update button bindings

src/main/java/frc/robot/subsystems/CoralIntake.java, src/main/java/frc/robot/subsystems/StateMachine.java
brake mode seems to be good enough with the gear ratio on the coral intake, so this will prevent oscillations resulting from hitting a wall or something
please test
=> Stop PID Loop when at setpoint

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/Elevator.java, src/main/java/frc/robot/subsystems/StateMachine.java
Ready Algae removal goes to retract when it shouldnt
=> New Algae Removal

src/main/java/frc/robot/subsystems/drive/DriveSubsystem.java
=> Fix angle adjustment

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/subsystems/Dragon.java, src/main/java/frc/robot/subsystems/StateMachine.java, vendordeps/libgrapplefrc2025.json
This does not affect controls or states, simply just puts a boolean on smart dashboard. Detection zone may need tuning
If we decide it's good, then we can use it in auto in another PR.
=> Add laser CAN to detect L4 alignment

src/main/java/frc/robot/subsystems/StateMachine.java
Test retract climb in parallel with elevator homing
=> Retract climb in parallel with elevator homing
